version: "3.7"

services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "62181:2181"
    networks:
      - default

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    networks:
      - default
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "legals:1:1,offices:1:1,payments:1:1,documents:1:1,rids_statuses:1:1,print_forms:1:1"
      KAFKA_GROUP_ID: "companydoc-group-id"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "10002:8080"
    environment:
      # Настройки для подключения к Kafka
      KAFKA_CLUSTERS_0_NAME: kafka_project
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPERCONNECT: zookeeper:2181
      KAFKA_CLUSTERS_0_DEFAULT_TOPIC: user
    depends_on:
      - kafka
    networks:
      - default

#      # Включение базовой аутентификации
#      SPRING_SECURITY_USER_NAME: login  # Логин
#      SPRING_SECURITY_USER_PASSWORD: pass

networks:
  default:
    external: true
    name: ${NETWORK_NAME}