version: "3.7"

services:
  project:
    restart: always
    build:
      context: ./..
      dockerfile: deployment/outbox/Dockerfile
      args:
        PROJECT: outbox
    ports:
      - "10001:10001"
    networks:
      - default


networks:
  default:
    external: true
    name: ${NETWORK_NAME}