version: "3.7"

services:
  postgresql-db:
    restart: always
    image: postgres:16
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - 'postgresql_data:/var/lib/cli/data'
    ports:
      - "5435:5432"

  migrate:
    build:
      context: ./..
      dockerfile: deployment/goose/Dockerfile
    environment:
      DB_HOST: postgresql-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      DB_CONN: "postgres://postgres:postgres@postgresql-db:5432/postgres?sslmode=disable"
    volumes:
      - ./migrations:/migrations
    depends_on:
      - postgresql-db

networks:
  default:
    external: true
    name: ${NETWORK_NAME}

volumes:
  postgresql_data:
