FROM golang:1.25-alpine AS builder
WORKDIR /app

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -mod=vendor -o /out/consumer-demo ./pkg/adapters/kafka/example/cmd/consumer-demo

FROM alpine:3.20
RUN adduser -D -u 10001 app
USER app
WORKDIR /home/app
COPY --from=builder /out/consumer-demo /usr/local/bin/consumer-demo

EXPOSE 2113
ENTRYPOINT ["/usr/local/bin/consumer-demo"]
