apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: auth-local
spec:
  ports:
    - name: ui
      port: 16686
      targetPort: ui
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
  selector:
    app: jaeger
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: auth-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      enableServiceLinks: false
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.58
          imagePullPolicy: IfNotPresent
          env:
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
          ports:
            - name: ui
              containerPort: 16686
            - name: otlp-http
              containerPort: 4318
          readinessProbe:
            httpGet:
              path: /
              port: ui
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 12
