apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-init
  namespace: auth-local
spec:
  backoffLimit: 6
  template:
    metadata:
      labels:
        app: kafka-init
    spec:
      enableServiceLinks: false
      restartPolicy: OnFailure
      containers:
        - name: kafka-init
          image: confluentinc/cp-kafka:7.6.0
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -ec
            - |
              kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic users.created --partitions 3 --replication-factor 1
              kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic users.vk.created --partitions 3 --replication-factor 1
